// var country_list = ["Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla","Antigua &amp; Barbuda","Argentina","Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados","Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia &amp; Herzegovina","Botswana","Brazil","British Virgin Islands","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon","Cape Verde","Cayman Islands","Chad","Chile","China","Colombia","Congo","Cook Islands","Costa Rica","Cote D Ivoire","Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic","Denmark","Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea","Estonia","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Polynesia","French West Indies","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland","Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana","Haiti","Honduras","Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel","Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos","Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau","Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Mauritania","Mauritius","Mexico","Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Namibia","Nepal","Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria","Norway","Oman","Pakistan","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines","Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda","Saint Pierre &amp; Miquelon","Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia","Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain","Sri Lanka","St Kitts &amp; Nevis","St Lucia","St Vincent","St. Lucia","Sudan","Suriname","Swaziland","Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor L'Este","Togo","Tonga","Trinidad &amp; Tobago","Tunisia","Turkey","Turkmenistan","Turks &amp; Caicos","Uganda","Ukraine","United Arab Emirates","United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Virgin Islands (US)","Yemen","Zambia","Zimbabwe"];



// E:\Project\NodeJs\New folder>node index
export const countries = [
  { key: 'Afghanistan', text: 'Afghanistan', value: 'Afghanistan' },
  { key: 'Albania', text: 'Albania', value: 'Albania' },
  { key: 'Algeria', text: 'Algeria', value: 'Algeria' },
  { key: 'Andorra', text: 'Andorra', value: 'Andorra' },
  { key: 'Angola', text: 'Angola', value: 'Angola' },
  { key: 'Anguilla', text: 'Anguilla', value: 'Anguilla' },
  {
    key: 'Antigua and Barbuda',
    text: 'Antigua and Barbuda',
    value: 'Antigua and Barbuda'
  },
  { key: 'Argentina', text: 'Argentina', value: 'Argentina' },
  { key: 'Armenia', text: 'Armenia', value: 'Armenia' },
  { key: 'Aruba', text: 'Aruba', value: 'Aruba' },
  { key: 'Australia', text: 'Australia', value: 'Australia' },
  { key: 'Austria', text: 'Austria', value: 'Austria' },
  { key: 'Azerbaijan', text: 'Azerbaijan', value: 'Azerbaijan' },
  { key: 'Bahamas', text: 'Bahamas', value: 'Bahamas' },
  { key: 'Bahrain', text: 'Bahrain', value: 'Bahrain' },
  { key: 'Bangladesh', text: 'Bangladesh', value: 'Bangladesh' },
  { key: 'Barbados', text: 'Barbados', value: 'Barbados' },
  { key: 'Belarus', text: 'Belarus', value: 'Belarus' },
  { key: 'Belgium', text: 'Belgium', value: 'Belgium' },
  { key: 'Belize', text: 'Belize', value: 'Belize' },
  { key: 'Benin', text: 'Benin', value: 'Benin' },
  { key: 'Bermuda', text: 'Bermuda', value: 'Bermuda' },
  { key: 'Bhutan', text: 'Bhutan', value: 'Bhutan' },
  { key: 'Bolivia', text: 'Bolivia', value: 'Bolivia' },
  {key: 'Bosnia and Herzegovina',text: 'Bosnia and Herzegovina',value: 'Bosnia and Herzegovina'},
  { key: 'Botswana', text: 'Botswana', value: 'Botswana' },
  { key: 'Brazil', text: 'Brazil', value: 'Brazil' },
  {key: 'British Virgin Islands',text: 'British Virgin Islands',value: 'British Virgin Islands'},
  { key: 'Brunei', text: 'Brunei', value: 'Brunei' },
  { key: 'Bulgaria', text: 'Bulgaria', value: 'Bulgaria' },
  { key: 'Burkina Faso', text: 'Burkina Faso', value: 'Burkina Faso' },
  { key: 'Burundi', text: 'Burundi', value: 'Burundi' },
  { key: 'Cambodia', text: 'Cambodia', value: 'Cambodia' },
  { key: 'Cameroon', text: 'Cameroon', value: 'Cameroon' },
  { key: 'Cape Verde', text: 'Cape Verde', value: 'Cape Verde' },
  {key: 'Cayman Islands',text: 'Cayman Islands',value: 'Cayman Islands'},
  { key: 'Chad', text: 'Chad', value: 'Chad' },
  { key: 'Chile', text: 'Chile', value: 'Chile' },
  { key: 'China', text: 'China', value: 'China' },
  { key: 'Colombia', text: 'Colombia', value: 'Colombia' },
  { key: 'Congo', text: 'Congo', value: 'Congo' },
  { key: 'Costa Rica', text: 'Costa Rica', value: 'Costa Rica' },
  { key: "Côte d'Ivoire",text: "Côte d'Ivoire",value: "Côte d'Ivoire"},
  { key: 'Croatia', text: 'Croatia', value: 'Croatia' },
  { key: 'Cuba', text: 'Cuba', value: 'Cuba' },
  { key: 'Cyprus', text: 'Cyprus', value: 'Cyprus' },
  { key: 'Czech Republic',text: 'Czech Republic', value: 'Czech Republic'},
  { key: 'Denmark', text: 'Denmark', value: 'Denmark' },
  { key: 'Djibouti', text: 'Djibouti', value: 'Djibouti' },
  { key: 'Dominica', text: 'Dominica', value: 'Dominica' },
  {key: 'Dominican Republic',text: 'Dominican Republic',value: 'Dominican Republic'},
  { key: 'Ecuador', text: 'Ecuador', value: 'Ecuador' },
  { key: 'Egypt', text: 'Egypt', value: 'Egypt' },
  { key: 'El Salvador', text: 'El Salvador', value: 'El Salvador' },
  {
    key: 'Equatorial Guinea',
    text: 'Equatorial Guinea',
    value: 'Equatorial Guinea'
  },
  { key: 'Estonia', text: 'Estonia', value: 'Estonia' },
  { key: 'Ethiopia', text: 'Ethiopia', value: 'Ethiopia' },
  {
    key: 'Falkland Islands',
    text: 'Falkland Islands',
    value: 'Falkland Islands'
  },
  {
    key: 'Faroe Islands',
    text: 'Faroe Islands',
    value: 'Faroe Islands'
  },
  { key: 'Fiji', text: 'Fiji', value: 'Fiji' },
  { key: 'Finland', text: 'Finland', value: 'Finland' },
  { key: 'France', text: 'France', value: 'France' },
  {
    key: 'French Polynesia',
    text: 'French Polynesia',
    value: 'French Polynesia'
  },
  { key: 'Gabon', text: 'Gabon', value: 'Gabon' },
  { key: 'Gambia', text: 'Gambia', value: 'Gambia' },
  { key: 'Georgia', text: 'Georgia', value: 'Georgia' },
  { key: 'Germany', text: 'Germany', value: 'Germany' },
  { key: 'Ghana', text: 'Ghana', value: 'Ghana' },
  { key: 'Gibraltar', text: 'Gibraltar', value: 'Gibraltar' },
  { key: 'Greece', text: 'Greece', value: 'Greece' },
  { key: 'Greenland', text: 'Greenland', value: 'Greenland' },
  { key: 'Grenada', text: 'Grenada', value: 'Grenada' },
  { key: 'Guatemala', text: 'Guatemala', value: 'Guatemala' },
  { key: 'Guinea', text: 'Guinea', value: 'Guinea' },
  {
    key: 'Guinea-Bissau',
    text: 'Guinea-Bissau',
    value: 'Guinea-Bissau'
  },
  { key: 'Guyana', text: 'Guyana', value: 'Guyana' },
  { key: 'Haiti', text: 'Haiti', value: 'Haiti' },
  { key: 'Honduras', text: 'Honduras', value: 'Honduras' },
  { key: 'Hong Kong', text: 'Hong Kong', value: 'Hong Kong' },
  { key: 'Hungary', text: 'Hungary', value: 'Hungary' },
  { key: 'Iceland', text: 'Iceland', value: 'Iceland' },
  { key: 'India', text: 'India', value: 'India' },
  { key: 'Indonesia', text: 'Indonesia', value: 'Indonesia' },
  { key: 'Iran', text: 'Iran', value: 'Iran' },
  { key: 'Iraq', text: 'Iraq', value: 'Iraq' },
  { key: 'Ireland', text: 'Ireland', value: 'Ireland' },
  { key: 'Isle of Man', text: 'Isle of Man', value: 'Isle of Man' },
  { key: 'Israel', text: 'Israel', value: 'Israel' },
  { key: 'Italy', text: 'Italy', value: 'Italy' },
  { key: 'Jamaica', text: 'Jamaica', value: 'Jamaica' },
  { key: 'Japan', text: 'Japan', value: 'Japan' },
  { key: 'Jersey', text: 'Jersey', value: 'Jersey' },
  { key: 'Jordan', text: 'Jordan', value: 'Jordan' },
  { key: 'Kazakhstan', text: 'Kazakhstan', value: 'Kazakhstan' },
  { key: 'Kenya', text: 'Kenya', value: 'Kenya' },
  { key: 'Kuwait', text: 'Kuwait', value: 'Kuwait' },
  {
    key: 'Kyrgyzstan',
    text: 'Kyrgyzstan',
    value: 'Kyrgyzstan'
  },
  { key: 'Laos', text: 'Laos', value: 'Laos' },
  { key: 'Latvia', text: 'Latvia', value: 'Latvia' },
  { key: 'Lebanon', text: 'Lebanon', value: 'Lebanon' },
  { key: 'Lesotho', text: 'Lesotho', value: 'Lesotho' },
  { key: 'Liberia', text: 'Liberia', value: 'Liberia' },
  { key: 'Libya', text: 'Libya', value: 'Libya' },
  {
    key: 'Liechtenstein',
    text: 'Liechtenstein',
    value: 'Liechtenstein'
  },
  { key: 'Lithuania', text: 'Lithuania', value: 'Lithuania' },
  { key: 'Luxembourg', text: 'Luxembourg', value: 'Luxembourg' },
  { key: 'Macau', text: 'Macau', value: 'Macau' },
  { key: 'Macedonia', text: 'Macedonia', value: 'Macedonia' },
  { key: 'Madagascar', text: 'Madagascar', value: 'Madagascar' },
  { key: 'Malawi', text: 'Malawi', value: 'Malawi' },
  { key: 'Malaysia', text: 'Malaysia', value: 'Malaysia' },
  { key: 'Maldives', text: 'Maldives', value: 'Maldives' },
  { key: 'Mali', text: 'Mali', value: 'Mali' },
  { key: 'Malta', text: 'Malta', value: 'Malta' },
  { key: 'Mauritania', text: 'Mauritania', value: 'Mauritania' },
  { key: 'Mauritius', text: 'Mauritius', value: 'Mauritius' },
  { key: 'Mexico', text: 'Mexico', value: 'Mexico' },
  { key: 'Moldova', text: 'Moldova', value: 'Moldova' },
  { key: 'Monaco', text: 'Monaco', value: 'Monaco' },
  { key: 'Mongolia', text: 'Mongolia', value: 'Mongolia' },
  { key: 'Montenegro', text: 'Montenegro', value: 'Montenegro' },
  { key: 'Montserrat', text: 'Montserrat', value: 'Montserrat' },
  { key: 'Morocco', text: 'Morocco', value: 'Morocco' },
  { key: 'Mozambique', text: 'Mozambique', value: 'Mozambique' },
  { key: 'Namibia', text: 'Namibia', value: 'Namibia' },
  { key: 'Nepal', text: 'Nepal', value: 'Nepal' },
  { key: 'Netherlands', text: 'Netherlands', value: 'Netherlands' },

  {
    key: 'New Caledonia',
    text: 'New Caledonia',
    value: 'New Caledonia'
  },
  { key: 'New Zealand', text: 'New Zealand', value: 'New Zealand' },
  { key: 'Nicaragua', text: 'Nicaragua', value: 'Nicaragua' },
  { key: 'Niger', text: 'Niger', value: 'Niger' },
  { key: 'Nigeria', text: 'Nigeria', value: 'Nigeria' },
  { key: 'Norway', text: 'Norway', value: 'Norway' },
  { key: 'Oman', text: 'Oman', value: 'Oman' },
  { key: 'Pakistan', text: 'Pakistan', value: 'Pakistan' },
  { key: 'Palestine', text: 'Palestine', value: 'Palestine' },
  { key: 'Panama', text: 'Panama', value: 'Panama' },
  {
    key: 'Papua New Guinea',
    text: 'Papua New Guinea',
    value: 'Papua New Guinea'
  },
  { key: 'Paraguay', text: 'Paraguay', value: 'Paraguay' },
  { key: 'Peru', text: 'Peru', value: 'Peru' },
  { key: 'Philippines', text: 'Philippines', value: 'Philippines' },
  { key: 'Poland', text: 'Poland', value: 'Poland' },
  { key: 'Portugal', text: 'Portugal', value: 'Portugal' },
  { key: 'Qatar', text: 'Qatar', value: 'Qatar' },
  { key: 'Reunion', text: 'Reunion', value: 'Reunion' },
  { key: 'Romania', text: 'Romania', value: 'Romania' },
  { key: 'Russia', text: 'Russia', value: 'Russia' },
  { key: 'Rwanda', text: 'Rwanda', value: 'Rwanda' },
  {
    key: 'Saint Pierre and Miquelon',
    text: 'Saint Pierre and Miquelon',
    value: 'Saint Pierre and Miquelon'
  },
  { key: 'San Marino', text: 'San Marino', value: 'San Marino' },
  { key: 'Saudi Arabia', text: 'Saudi Arabia', value: 'Saudi Arabia' },
  { key: 'Senegal', text: 'Senegal', value: 'Senegal' },
  { key: 'Serbia', text: 'Serbia', value: 'Serbia' },
  { key: 'Seychelles', text: 'Seychelles', value: 'Seychelles' },
  { key: 'Sierra Leone', text: 'Sierra Leone', value: 'Sierra Leone' },
  { key: 'Singapore', text: 'Singapore', value: 'Singapore' },
  { key: 'Slovakia', text: 'Slovakia', value: 'Slovakia' },
  { key: 'Slovenia', text: 'Slovenia', value: 'Slovenia' },
  { key: 'South Africa', text: 'South Africa', value: 'South Africa' },
  { key: 'South Korea', text: 'South Korea', value: 'South Korea' },
  { key: 'Spain', text: 'Spain', value: 'Spain' },
  { key: 'Sri Lanka', text: 'Sri Lanka', value: 'Sri Lanka' },
  {
    key: 'Saint Kitts and Nevis',
    text: 'Saint Kitts and Nevis',
    value: 'Saint Kitts and Nevis'
  },
  { key: 'St Lucia', text: 'St Lucia', value: 'St Lucia' },
  { key: 'Sudan', text: 'Sudan', value: 'Sudan' },
  { key: 'Suriname', text: 'Suriname', value: 'Suriname' },
  { key: 'Swaziland', text: 'Swaziland', value: 'Swaziland' },
  { key: 'Sweden', text: 'Sweden', value: 'Sweden' },
  { key: 'Switzerland', text: 'Switzerland', value: 'Switzerland' },
  { key: 'Syria', text: 'Syria', value: 'Syria' },
  { key: 'Taiwan', text: 'Taiwan', value: 'Taiwan' },
  { key: 'Tajikistan', text: 'Tajikistan', value: 'Tajikistan' },
  { key: 'Tanzania', text: 'Tanzania', value: 'Tanzania' },
  { key: 'Thailand', text: 'Thailand', value: 'Thailand' },
  { key: "Timor-Leste", text: "Timor-Leste", value: "Timor-Leste" },
  { key: 'Togo', text: 'Togo', value: 'Togo' },
  {
    key: 'Trinidad and Tobago',
    text: 'Trinidad and Tobago',
    value: 'Trinidad and Tobago'
  },
  { key: 'Tunisia', text: 'Tunisia', value: 'Tunisia' },
  { key: 'Turkey', text: 'Turkey', value: 'Turkey' },
  {
    key: 'Turks and Caicos Islands',
    text: 'Turks and Caicos Islands',
    value: 'Turks and Caicos Islands'
  },
  { key: 'Uganda', text: 'Uganda', value: 'Uganda' },
  { key: 'Ukraine', text: 'Ukraine', value: 'Ukraine' },
  {
    key: 'United Arab Emirates',
    text: 'United Arab Emirates',
    value: 'United Arab Emirates'
  },
  {
    key: 'United Kingdom',
    text: 'United Kingdom',
    value: 'United Kingdom'
  },
  { key: 'Uruguay', text: 'Uruguay', value: 'Uruguay' },
  { key: 'Uzbekistan', text: 'Uzbekistan', value: 'Uzbekistan' },
  { key: 'Venezuela', text: 'Venezuela', value: 'Venezuela' },
  { key: 'Vietnam', text: 'Vietnam', value: 'Vietnam' },
  { key: 'Yemen', text: 'Yemen', value: 'Yemen' },
  { key: 'Zambia', text: 'Zambia', value: 'Zambia' },
  { key: 'Zimbabwe', text: 'Zimbabwe', value: 'Zimbabwe' }
]